### PR TITLE
DEVOPS-14083 - pin dependency decorator version

### PR DESCRIPTION
**Pull request by mayn**
see ticket DEVOPS-14083

### CODE REVIEW

**Review by dnb-markusd — CHANGES_REQUESTED** [review]
Looks good. Please provide evidence of testing.

**Comment by banderon1** [comment]
merge!

**Review by altuner — APPROVED** [review]

**Comment by mayn** [comment]
@dnb-markusd  its on the ticket
image

**Review by dnb-markusd — APPROVED** [review]

**Comment by mayn** [comment]
good looking out @banderon1  @gh4x

**Pull request merged**
