### PR TITLE
(10.3.0) INFRASYS-6263 - Adding revert function for failed jobs

### PR DESCRIPTION
**Pull request by adamjkeller**

### CODE REVIEW

**Comment by adamjkeller** [comment]
Pending:
- Unit Test Update

**Comment by adamjkeller** [comment]
```
akeller@akeller-MBPR License2Deploy (INFRASYS-6263 *):$ python License2Deploy/rolling_deploy.py -e qa -p dnbi-email -b 2 -P dnbi-deploy -a ami-f3f09f93 --revert
2015-11-11 13:57:29,725: INFO: Begin Logging...
2015-11-11 13:57:29,730: INFO: REVERTING: Removing new instances from autoscale group
2015-11-11 13:57:35,300: INFO: List of all Instance ID's and IP addresses in dnbi-backend-qa-dnbiemailASGqa-18Q77MNB6EXNN: {u'i-82f3f042': u'10.30.10.107', u'i-11efecd1': u'10.30.10.200', u'i-10efecd0': u'10.30.10.199', u'i-81f3f041': u'10.30.10.106'}
2015-11-11 13:57:35,808: INFO: New Instance List with IP Addresses: {u'i-82f3f042': u'10.30.10.107', u'i-81f3f041': u'10.30.10.106'}
2015-11-11 13:57:36,116: INFO: Removed i-82f3f042 from autoscale group
2015-11-11 13:57:36,341: INFO: Removed i-81f3f041 from autoscale group
2015-11-11 13:57:36,341: INFO: REVERT COMPLETE!
```

**Comment by kantselovich** [comment]
+1  Thank you @adamjkeller

**Comment by sbraverman** [comment]
+1

**Pull request merged**
